// Generated by scripts/sync-project-metadata.mjs. Do not hand-edit release facts.
export const release = {
  version: '1.0.0',
  status: 'Stable',
  skillCount: 12,
  workflowCount: 6,
  providerCount: 14,
  firstClassProviderCount: 11,
  evalCount: 7,
  agentOsVersion: '3.0.0',
  gsdVersion: '1.12.0',
  source: 'RELEASE_MANIFEST.json snapshot',
} as const;

export const releaseFacts = [
  [String(release.skillCount), 'Agent Skills'],
  [String(release.workflowCount), 'delivery workflows'],
  [String(release.providerCount), 'tracked provider targets'],
  [String(release.evalCount), 'deterministic runtime evals'],
] as const;
